---

- block:
    - name: Make sure /etc/resolv.conf exists
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf

    - name: Create /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: not resolv_conf.stat.exists

    - name: Add DNS server(s) into /etc/resolv.conf
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        regexp: "^nameserver {{ item }}"
        insertbefore: '^options'
        line: "nameserver {{ item }}"
        unsafe_writes: true  # to prevent failures in CI
      loop: "{{ nameservers }}"
  when:
    - nameservers is defined
    - nameservers | length > 0
  tags: dns, nameservers

...
