---
- name: Clean yum cache
  ansible.builtin.command: yum clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '7'

- name: Clean dnf cache
  ansible.builtin.command: dnf clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
  when: ansible_os_family == "Debian"

- name: Install the latest version of PostgreSQL packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ postgresql_packages }}"
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
...
