---
- name: "Update docker network(s)"
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: "Create docker network: test_docker_network"
      community.docker.docker_network:
        name: test_docker_network
        driver: bridge
        driver_options:
          com.docker.network.driver.mtu: 1440
        enable_ipv6: false
        internal: false
        ipam_config:
          - subnet: 10.172.1.0/24
            gateway: 10.172.1.1
        force: true
        state: present
        labels:
          owner: molecule

...
