---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
      remote_tmp: "~/.ansible/tmp"
      allow_world_readable_tmpfiles: false
      timeout: 60
  inventory:
    links:
      group_vars: ../../group_vars/
  playbooks:
    prepare: prepare.yml

scenario:
  create_sequence:
    - prepare
    - create
  converge_sequence:
    - prepare
    - create
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - prepare
    - create
    - converge
    #    - idempotence  # >> role:patroni,task:"data directory check result"
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
